name: CI
on: [push, pull_request]
env:
  HTTPTOOLKIT_SERVER_DISABLE_AUTOUPDATE: 1 # Don't try to autoupdate during tests etc
  UI_VERSION: ${{ github.sha }}
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    container:
      image: httptoolkit/act-build-base:v3.0.0
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - run: npm install -g npm@^8

      - name: Set up JDK 11 for Java testing
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: adopt-hotspot

      - run: npm ci
        env:
          NPM_CONFIG_UNSAFE_PERM: true

      - run: npm run build

      - run: |
          curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          curl -sL https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y p7zip-full xterm

      - run: npm run build:default
        env:
          NPM_CONFIG_UNSAFE_PERM: true

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
          if-no-files-found: error

  publish-pages:
    name: Publish Pages
    if: github.event_name == 'push' && github.ref == 'refs/heads/fork'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
        
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
